---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: QRadar CE VM template
    vmware_guest:
          hostname: 192.168.1.100
          username: administrator@sso.local
          password: PasswordHere
          validate_certs: no
          esxi_hostname: 192.168.1.102
          datacenter: Homelab
          name: QRadar_ce
          state: poweredoff
          is_template: yes
          guest_id: centos7_64Guest
          disk:
          - size_gb: 120
            type: thin
            datastore: datastore3
          hardware:
             memory_mb: 8000
             num_cpus: 2
             scsi: paravirtual
          networks:
            - name: VM Network
              device_type: vmxnet3
...
