---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: QRadar CE VM template
    vmware_guest:
          hostname: 192.168.1.200
          username: administrator@vsphere.local
          password: password-here
          validate_certs: no
          esxi_hostname: 192.168.1.100
          datacenter: homelab
          folder: /qradar
          name: QRadarCE
          state: poweredoff
          guest_id: centos7_64Guest
          disk:
          - size_gb: 120
            type: thin
            datastore: datastore3
          hardware:
             memory_mb: 8000
             num_cpus: 2
             scsi: paravirtual
          cdrom:
            type: "iso"
            iso_path: "[datastore1] path/to/file.iso"
          networks:
            - name: VM Network
              device_type: vmxnet3
...
